# Site settings
## About
title: Site C
author: Benno Bielmeier
email: c@bbenno.com
description: C{ool,omputer,ode} -- stuff
## Technical
timezone: Europe/Berlin

# Jekyll
theme: minima
exclude:
- Gemfile
- Gemfile.lock
include:
- _pages
plugins:
- jekyll-asciidoc

# AsciiDoc[tor]
asciidoc: {}
asciidoctor: {}

# Minima (Theme) settings
github_username: bbenno
