= Thymeleaf
:icons: font
:source-language: java
:keywords: Thymeleaf, Java, Entity, HTML5, XHTML
:badge: https://shields.io/badge/
:gh-badge: {badge}-GitHub-grey?logo=GitHub
:doc-badge: {badge}-Documentation-grey
:gh-url: https://github.com/
:tl-url: https://www.thymeleaf.org/
:thymeleaf-version: 3.0
:thymeleaf-green: 005F0F

image:{badge}-Website-grey?logo=Thymeleaf[link="{tl-url}"]
image:{doc-badge}?logo=Thymeleaf[link="{tl-url}documentation.html"]
image:{gh-badge}[link="{gh-url}thymeleaf/thymeleaf"] +
image:{badge}Documentation-Usage-{thymeleaf-green}[link="https://www.thymeleaf.org/doc/tutorials/{thymeleaf-version}/usingthymeleaf.html"]
image:{badge}Documentation-Spring-{thymeleaf-green}[link="https://www.thymeleaf.org/doc/tutorials/{thymeleaf-version}/thymeleafspring.html"]

[quote, '{tl-url}doc/tutorials/3.0/usingthymeleaf.html#introducing-thymeleaf[Thymeleaf documentation]']
____
Thymeleaf is a modern server-side Java template engine for both web and standalone environments, capable of processing HTML, XML, JavaScript, CSS and even plain text.
____

== Standard Expression

[horizontal]
`${...}`:: Variable expression
`*{...}`:: Selection expression
`#{...}`:: Message (i18n) expression
`@{...}`:: Link (URL) expression
`~{...}`:: <<Fragmentation,Fragment expression>>

== Fragmentation

[horizontal]
`th:insert`:: Insert fragment as the body of host tag
`th:replace`:: Replace host tag with fragment
`th:include`:: Insert contents of fragment as body of host tag

.Basic usecase
* Fragment definition
+
[source]
----
<HTML_TAG ... th:fragment="FRAG_NAME">
  ...
</HTML_TAG>
----
* Fragment usage
+
[source]
----
<HTML_TAG ... th:[insert|replace|include]="REL_FILE_PATH {two-colons} SELECTOR">...</HTML_TAG>`
----

.Parameterized usecase
* Fragment definition
+
[source]
----
<HTML_TAG ... th:fragment="FRAG_NAME (var1,var2)">
  <p th:text="${var1} + ' and ' + ${var2}">...</p>
  ...
</HTML_TAG>
----
* Fragment usage
+
[source]
----
<HTML_TAG ... th:[insert|replace|include]="REL_FILE_PATH {two-colons} SELECTOR (${val1},${val2})">...</HTML_TAG>`
----

== Extend

=== Thymeleaf Layout Dialect

image:{gh-badge}[link="{gh-url}ultraq/thymeleaf-layout-dialect"]
image:{doc-badge}[link="https://ultraq.github.io/thymeleaf-layout-dialect/"]

=== Security Dialect

NOTE: Requires https://search.maven.org/classic/#search%7Cga%7C1%7Cthymeleaf-extras-springsecurity5[`thymeleaf-extras-springsecurity`] as dependency.

`sec:authorize`::
  control displayed content
`sec:authentication`::
  access to authentication object
