= Spring Boot
:icons: font
:source-language: java
:keywords: Spring, Java, JPA, Entity
:badge: https://shields.io/badge
:hibernate-version: 5.4
:hibernate-docs-url: https://docs.jboss.org/hibernate/orm/{hibernate-version}/javadocs

image:{badge}/-Website-grey?logo=Spring[link="https://spring.io/projects/spring-boot"]
image:{badge}/-Documentation-grey?logo=Spring[link="https://docs.spring.io/spring-boot/docs/2.3.5.RELEASE/reference/htmlsingle/"]
image:{badge}/-GitHub-grey?logo=GitHub[link="https://github.com/spring-projects/spring-boot"]

[[Entity]]
== Entity (Hibernate)

image:{badge}/-Website-grey?logo=Hibernate[link="https://hibernate.org"]
image:{badge}/-Documentation-grey?logo=Hibernate[link="https://hibernate.org/orm/documentation/{hibernate-version}/"]

=== Relations

[cols="2", options="header"]
|===

|multiplicity
|annotation

|[[One-to-One, `1:1`]]`1:1`
|{hibernate-docs-url}/org/hibernate/mapping/OneToOne.html[`@OneToOne`]

|[[One-to-Many, `1:n`]]`1:n`
|{hibernate-docs-url}/org/hibernate/mapping/OneToMany.html[`@OneToMany`]

|[[Many-to-One, `n:1`]]`n:1`
|{hibernate-docs-url}/org/hibernate/mapping/ManyToOne.html[`@ManyToOne`]

|[[Many-to-Many, `n:n`]]`n:n`
|{hibernate-docs-url}/org/hibernate/mapping/ManyToMany.html[`@ManyToMany`]

|===

These annotations can optionally be combined with either {hibernate-docs-url}/org/hibernate/mapping/JoinColumn.html[`@JoinColumn`] (<<One-to-One>>, <<One-to-Many>>, <<Many-to-One>>) or {hibernate-docs-url}/org/hibernate/mapping/JoinTable[`@JoinTable`] (<<Many-to-Many>>).

.Optional annotation elements with default values
[cols="5", options="header"]
|===

|annotation
|<<One-to-One>>
|<<One-to-Many>>
|<<Many-to-One>>
|<<Many-to-Many>>

|`mappedBy`
|✅
|✅
|✅
|✅

|`fetch`
|✅ `EAGER`
|✅ `LAZY`
|✅ `EAGER`
|✅ `LAZY`

|`cascade`
|✅ `{}`
|✅ `{}`
|✅ `{}`
|✅ `{}`

|`orphanRemove`
|✅ `false`
|✅ `false`
|❌
|❌

|`optional`
|✅ `true`
|❌
|✅ `true`
|❌

|===

=== Validation

After adding https://search.maven.org/search?q=g:org.springframework.boot%20AND%20a:spring-boot-starter-validation[`spring-boot-starter-validation`] as dependency the following annotaions of the package `javax.validation` can be used.

* `@Null`, `@NotNull`
* `@Max`, `@Min`
* `@Future`, `@FutureOrPresent`, `@Past`, `@PastOrPresent`
* `@Pattern`, `@Email`, `@Size`
* `@AssertTrue`, `@AssertFalse`
* `@Digits`, `@DecimalMax`, `@DecimalMin`, `@Positive`, `@PositiveOrZero`, `@Negative`, `@NegativeOrZero`

=== Auto Generated Values

`GenerationType.AUTO` (default)::
  The Persistence provider chooses the generation strategy.
  Hibernate selects a generation strategy based on the database specific dialect, mostly `GenerationType.SEQUENCE`.
`GenerationType.IDENTITY`::
  It relies on an auto-incremented database column and lets the database generate a new value with each insert operation.
  Using Hibernate it has some performance drawbacks.footnote:[Hibernate requires a primary key value for each managed entity and therefore has to perform the insert statement immediately. This prevents it from using different optimization techniques like JDBC batching.]
`GenerationType.SEQUENCE`::
  Database sequence is used to generate unique values.
  Although it requires additional select statements to get the next value from a database sequence this has no performance impact for most applications.
`GenerationType.TABLE`::
  This strategy should rarely used nowadays.
  It simulates a sequence by storing and updating its current value in a database table which requires the use of pessimistic locks which put all transactions into a sequential order.
  This slows down the application.
  Therefore, the `GenerationType.SEQUENCE` should be preferred.

=== Inheritance

Querying a base class will retrieve all the sub-class entities as well.
If this behavior is unintended add the `@Ploymorphism` annotation to the sub-class definition with type `EXPLICIT`

[source]
----
@Entity
@Polymorphism(type = PolymorphismType.EXPLICIT)
public class A implements S { ... }
----

==== MappedSuperclass

[source]
----
@MappedSuperclass
public class S { @Id private long id; } <1>

@Entity
public class A extends { private String s; } <2>
----
<1> The *MappedSuperclass* `S` will not be persisted  in the database and can not contain associations with other entities.
<2> The `A` table has two columns for the declared and inherited fields.

==== Single Table

This strategy creates one table for each class hierarchy.
It is the default strategy chosen by JPA.

Since the records for all entities will be in the same table, a way to differentiate between them is needed.

.Discrimination types
. <<Discriminator Values>> `DTYPE`
. <<Discriminator Formula>>

===== Discriminator Values

[source]
----
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "class_type", discriminatorType = DiscriminatorType.INTEGER) <1>
public class S { @Id private long id; }

@Entity
@DiscriminatorValue("1") <2>
public class A extends S { private String s1; }

@Entity
@DiscriminatorValue("2") <2>
public class B extends S { private String s2 }
----
<1> Differentiate sub-class entities by `integer`column called `class_type`.
<2> Values of sub-class records of `class_type` column.

There are two other predefined values that the annotation can take.

.Predefined annotation values
[horizontal]
`@DiscriminatorValue("null")`:: Any row without a discriminator value will be mapped to the entity class with this annotation. This can be applied to the root class of the hierarchy.
`@DiscriminatorValue("not null")`:: Any row with a discriminator value not matching any of the ones associated with entity definitions will be mapped to the class with this annotation.

===== Discriminator Formula

Instead of a column, the `@DiscriminatorFormula` annotation can be used to determine the differentiating values.

[horizontal]
Advantage:: polymorphic query performance -> only one table needs to be accessed when querying parent entities
Disadvantage:: `NOT NULL` constraints on sub-class entity properties are no longer usable

[source]
----
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorFormula("case when s is not null then 1 else 2 end") <1>
public class S { @Id private long id; }

@Entity
@DiscriminatorValue("1") <2>
public class A extends S { private String s; }

@Entity
@DiscriminatorValue("2") <2>
public class B extends S { private String t; }
----
<1> Formula replaces type column.
<2> Entity annotations remain the same.

==== Joined Table

Each class in the hierarchy is mapped to its table.
All tables will have an identifier column named after the parent class, which will be used for joining them when needed.
The disadvantage of this inheritance mapping method is that retrieving entities requires joins between tables, which can result in lower performance for large numbers of records.

[source]
----
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class S { @Id private long id; }

@Entity
@PrimaryKeyJoinColumn(name = "aId") // The "a" in `aId` is not an article but the name of the class.
public class A extends S { private String s; }
----

==== Table per Class

The strategy maps each entity to its table which contains all the properties of the entity, including the ones inherited.
The resulting schema is similar to the one using <<MappedSuperclass>>, but unlike it, a table per class will indeed define entities for parent classes, allowing associations and polymorphic queries as a result.

The strategy is not very different from mapping each entity without inheritance.
The distinction is apparent when querying the base class, which will return all the sub-class records as well by a `UNION` statement (performance impact!) in the background.

[source]
----
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public class S { @Id private long id; }

@Entity
public class A { private String s; }
----

[[MVC]]
== Model-View-Controller (MVC)

For basic usage consider the https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC] guide on https://spring.io[spring.io].

.Schematic overview
[plantuml]
....
@startuml
skinparam monochrome true
hide circle

package "Presentation" {
  class Model
  class Controller <<Controller>>
  class MyController <<Controller>> <<Scope>>
  class HTML5 <<View>>

  MyController "1" x-right-> "1" Model
  MyController "1" x-left-> "1" HTML5
  Controller "1" --> "*" HTML5
  Controller "1" x--> "*" MyController
}

package "Business" {
  class Bean <<Service>>
}

package "Persistence" {
  class Repository<E, K>
  class Entity <<Entity>>

  Repository -left-> Entity
}

MyController -down- Bean
Bean -down- Repository
@enduml
....

=== Model

Unlike in Ruby on Rails, the model class  in spring is not implemented by the developer.
It is a key-value storage in which data of a request and/or response is stored.

=== View

As Jakarta Server Pages (JSP) is not recommended, use link:java-thymeleaf.adoc[Thymeleaf].

=== Controller

`@Controller` is the central annotation to mark a class as MVC-controller.

[source]
----
@Controller
public class EntityController {
  @RequestMapping("/path/first")
  public ModelAndView showFirstView() {
    return new ModelAndView("firstView", "entity", new Entity());
  }
  
  @RequestMapping("/path/second")
  public String showSecondView(
      @Valid @ModelAttribute("entity") Entity entity,
      BindingResult result,
      ModelMap model) {
    if (result.hasErrors()) {
      return "error";
    }
    model.addAttribute("entity_attribute", entity.getAttribute());
    return "secondView";
  }
}
----

==== JSON

* `@RequestBody`: return value is serialized to body of HTTP Response
+
[source]
----
@PutMapping("/{id}")
public @ResponseBody void update(@RequestBody Entity entity, @PathVariable long id) {
    entityService.update(entity);
}
----
* `@ResponseBody`: body of HTTP Request is deserialized to particular entity
+
[source]
----
@RequestMapping("/{id}")
public @ResponseBody Entity findById(@PathVariable long id) {
    return entityService.findById(id);
}
----
* `@RestController` = `@Controller` + `@ResponseBody`

==== Redirect

There are several ways to redirect requests.
<<RedirectView>> and <<prefix_redirect>> will redirect via the https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302[HTTP 302] response status code.
<<prefix_forward>> will not redirect but forward the request internally. The client will not be aware of this due to the URL in the browser remaining unchanged.

Furthermore, the <<prefix_redirect>> approach should be used in preference to <<RedirectView>> for two reasons.
First, using `RedirectView` couples the code closely to the https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/view/RedirectView.html[Spring API].
Second, the controller operation will always redirect and lacks of flexibility.

There also is another alternative without the usage of any prefix: using `RedirectView` bean in the configuration.
This approach will not be considered.

[[RedirectView]]
===== Redirect with the _RedirectView_

`RedirectView` will trigger a `HttpServletResponse.sendRedirect()` -- which will perform the actual redirect.

[source]
----
@Controller
public class RedirectController {
    @RequestMapping("/redirect")
    public RedirectView redirect(RedirectAttributes attributes) {
        attributes.addFlashAttribute("attrFlash", "redirected");
        attributes.addAttribute("attr", "redirected");
        return new RedirectView("target");
    }
}
----

[[prefix_redirect]]
===== Redirect with the prefix _redirect_

Using the prefix _redirect_ the controller is not aware of the redirection.
`UrlBasedViewResolver` will recognize the prefix as a special indication that a redirect needs to happen.
The rest of the view name will be used as the redirect URL, relatively to the current Servlet context.

[source]
----
@Controller
public class RedirectController {
    @RequestMapping("/redirect")
    public ModelAndView redirect(ModelMap model) {
        model.addAttribute("attr", "redirected");
        // Following redirect is relative to the current Servlet context.
        return new ModelAndView("redirect:/target", model);
    }
}
----

[[prefix_forward]]
===== Forward With the prefix _forward_

Like the _redirect_ prefix, the _forward_ prefix will be resolved by `UrlBasedViewResolver`.
An InternalResourceView is being created which performs a `RequestDispatcher.forward()` to the target view.

[source]
----
@Controller
public class RedirectController {
    @GetMapping("/forward")
    public ModelAndView forward(ModelMap model) {
        model.addAttribute("attr", "forwarded");
        return new ModelAndView("forward:/target", model);
    }
}
----
