= Thymeleaf
:icons: font
:source-language: java
:keywords: Thymeleaf, Java, Entity, HTML5, XHTML
:badge: https://shields.io/badge
:gh-badge: https://shields.io/badge/-GitHub-grey?logo=GitHub
:gh-url: https://github.com/
:tl-url: https://www.thymeleaf.org/

image:{badge}/-Website-grey?logo=thymeleaf[link="{tl-url}"]
image:{badge}/-Documentation-grey?logo=thymeleaf[link="{tl-url}documentation.html"]
image:{badge}/-Documentation-grey?logo=GitHub[link="{gh-url}thymeleaf/thymeleaf"]

[quote, '{tl-url}doc/tutorials/3.0/usingthymeleaf.html#introducing-thymeleaf[Thymeleaf documentation]']
____
Thymeleaf is a modern server-side Java template engine for both web and standalone environments, capable of processing HTML, XML, JavaScript, CSS and even plain text.
____

== Standard Expression

[horizontal]
`${...}`:: Variable expression
`*{...}`:: Selection expression
`#{...}`:: Message (i18n) expression
`@{...}`:: Link (URL) expression
`~{...}`:: <<Fragmentation,Fragment expression>>

== Fragmentation

[horizontal]
`th:insert`:: Insert fragment as the body of host tag
`th:replace`:: Replace host tag with fragment
`th:include`:: Insert contents of fragment as body of host tag

.Basic usecase
* Fragment definition
+
[source]
----
<HTML_TAG ... th:fragment="FRAG_NAME">
  ...
</HTML_TAG>
----
* Fragment usage
+
[source]
----
<HTML_TAG ... th:[insert|replace|include]="REL_FILE_PATH {two-colons} SELECTOR">...</HTML_TAG>`
----

.Parameterized usecase
* Fragment definition
+
[source]
----
<HTML_TAG ... th:fragment="FRAG_NAME (var1,var2)">
  <p th:text="${var1} + ' and ' + ${var2}">...</p>
  ...
</HTML_TAG>
----
* Fragment usage
+
[source]
----
<HTML_TAG ... th:[insert|replace|include]="REL_FILE_PATH {two-colons} SELECTOR (${val1},${val2})">...</HTML_TAG>`
----

== Extend

=== Thymeleaf Layout Dialect

image:{gh-badge}[link="{gh-url}ultraq/thymeleaf-layout-dialect"]
